# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - HealthyPlus

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: List generated files
        run: |
          echo "Listing files in api-gateway target"
          dir ${{ github.workspace }}/api-gateway/target
          echo "Listing files in discovery-server target"
          dir ${{ github.workspace }}/discovery-server/target
          echo "Listing files in iotdevice-service target"
          dir ${{ github.workspace }}/iotdevice-service/target
          echo "Listing files in measurement-service target"
          dir ${{ github.workspace }}/measurement-service/target
          echo "Listing files in patient-service target"
          dir ${{ github.workspace }}/patient-service/target
          echo "Listing files in user-service target"
          dir ${{ github.workspace }}/user-service/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: |
            ${{ github.workspace }}/api-gateway/target/*.jar
            ${{ github.workspace }}/discovery-server/target/*.jar
            ${{ github.workspace }}/iotdevice-service/target/*.jar
            ${{ github.workspace }}/measurement-service/target/*.jar
            ${{ github.workspace }}/patient-service/target/*.jar
            ${{ github.workspace }}/user-service/target/*.jar

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBADCE32497F4BC5B9223DA5C1161E70 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_65D1D6FA00CF478B9893488A3B2A466C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70804268E6A3410FA8CE427D160F5948 }}

      - name: Deploy api-gateway to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthyPlus-api-gateway'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/api-gateway-1.0.0-SNAPSHOT.jar'

      # Deploy discovery-server
      - name: Deploy discovery-server to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthyPlus-discovery-server'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/discovery-server-1.0.0-SNAPSHOT.jar'

      # Deploy iotdevice-service
      - name: Deploy iotdevice-service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthyPlus-iotdevice-service'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/iotdevice-service-1.0.0-SNAPSHOT.jar'

      # Deploy measurement-service
      - name: Deploy measurement-service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthyPlus-measurement-service'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/measurement-service-1.0.0-SNAPSHOT.jar'

      # Deploy patient-service
      - name: Deploy patient-service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthyPlus-patient-service'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/patient-service-1.0.0-SNAPSHOT.jar'

      # Deploy user-service
      - name: Deploy user-service to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HealthyPlus-user-service'
          slot-name: 'Production'
          package: '${{ github.workspace }}/java-app/user-service-1.0.0-SNAPSHOT.jar'
          
